from machine import Pin

CS1 = Pin(0, Pin.OUT)
CS2 = Pin(1, Pin.OUT)
RST = Pin(21, Pin.OUT)
E = Pin(7, Pin.OUT)
RW = Pin(6, Pin.OUT)
RS = Pin(5, Pin.OUT)
DB0 = Pin(8, Pin.OUT)
DB1 = Pin(9, Pin.OUT)
DB2 = Pin(10, Pin.OUT)
DB3 = Pin(11, Pin.OUT)
DB4 = Pin(12, Pin.OUT)
DB5 = Pin(13, Pin.OUT)
DB6 = Pin(14, Pin.OUT)
DB7 = Pin(15, Pin.OUT)

E.value(1)
CS1.value(0)
CS2.value(0)
RST.value(0)
def turnOnLCD():
    RS.value(0)
    RW.value(0)
    DB7.value(0)
    DB6.value(0)
    DB5.value(1)
    DB4.value(1)
    DB3.value(1)
    DB2.value(1)
    DB1.value(1)
    DB0.value(1)